export enum ConversationIntent {
  // === INTENTS ORIGINALES (lenguaje natural) ===
  SMALL_TALK = 'SMALL_TALK',
  VIEW_MENU = 'VIEW_MENU',
  ASK_QUESTION = 'ASK_QUESTION',
  ORDER_FOOD = 'ORDER_FOOD',
  TRACK_ORDER = 'TRACK_ORDER',
  PAYMENT_REQUEST = 'PAYMENT_REQUEST',
  SUPPORT = 'SUPPORT',
  BUSINESS_HOURS = 'BUSINESS_HOURS',
  BUSINESS_LOCATION = 'BUSINESS_LOCATION',
  DELIVERY_INFO = 'DELIVERY_INFO',
  PAYMENT_METHODS = 'PAYMENT_METHODS',
  PRODUCT_QUERY = 'PRODUCT_QUERY',
  PRODUCT_ATTRIBUTE_QUESTION = 'PRODUCT_ATTRIBUTE_QUESTION',
  GENERAL_QUESTION = 'GENERAL_QUESTION',
  // === NUEVOS: Acciones específicas de pedido (detectadas por LLM) ===
  REMOVE_ITEM = 'REMOVE_ITEM',           // "sacá la pizza"
  MODIFY_QUANTITY = 'MODIFY_QUANTITY',   // "cambiá a 3"
  ADD_PRODUCT = 'ADD_PRODUCT',           // "quiero una hamburguesa" (específico)
  CONFIRM_ADD = 'CONFIRM_ADD',
  // === NUEVOS: Interacciones de botones (payloadId) ===
  SELECT_PRODUCT = 'SELECT_PRODUCT',
  SELECT_ORDER_PRODUCT = 'SELECT_ORDER_PRODUCT',
  ORDER_SEARCH_PAGE = 'ORDER_SEARCH_PAGE',
  CATEGORY_PAGE = 'CATEGORY_PAGE',
  CATEGORY_LIST_PAGE = 'CATEGORY_LIST_PAGE',
  /** Lista de productos filtrada por tag de categoría (p. ej. MENU_BY_TAG:STARTER:1). */
  MENU_BY_TAG = 'MENU_BY_TAG',
  CATEGORY = 'CATEGORY',
  ADD_ITEM = 'ADD_ITEM',                 // Botón "Agregar al pedido"
  /** Ver listado de complementos guardado en metadata (tras puente con botones). */
  COMPLEMENT_SHOW_SUGGESTIONS = 'COMPLEMENT_SHOW_SUGGESTIONS',
  CHECKOUT = 'CHECKOUT',
  CANCEL_ORDER = 'CANCEL_ORDER',
  END_CONVERSATION = 'END_CONVERSATION',
  VIEW_MENU_RETURN = 'VIEW_MENU_RETURN',
  CONFIRM_REMOVE = 'CONFIRM_REMOVE',     // Botón "Sí, remover"
  CANCEL_REMOVE = 'CANCEL_REMOVE',
  VIEW_CART = 'VIEW_CART',
  VIEW_CART_FOR_EDITION = 'VIEW_CART_FOR_EDITION',
  SELECT_CART_ITEM = 'SELECT_CART_ITEM',
  INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY',
  DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY',
  DECREASE_ITEM = 'DECREASE_ITEM',
  INCREASE_ITEM = 'INCREASE_ITEM',
  VIEW_ORDER = 'VIEW_ORDER',
  EDIT_ADDRESS = 'EDIT_ADDRESS',
  RESERVATION = 'RESERVATION',
  VIEW_RESERVATION = 'VIEW_RESERVATION',
  VIEW_QR = 'VIEW_QR',
  UNKNOWN = 'UNKNOWN',
  // adress intents
  ONBOARDING_START = 'ONBOARDING_START',
  ONBOARDING_SUBMIT_ADDRESS_TEXT = 'ONBOARDING_SUBMIT_ADDRESS_TEXT',
  ONBOARDING_SUBMIT_LOCATION = 'ONBOARDING_SUBMIT_LOCATION',
  ONBOARDING_CONFIRM_ADDRESS = 'ONBOARDING_CONFIRM_ADDRESS',
  ONBOARDING_EDIT_ADDRESS = 'ONBOARDING_EDIT_ADDRESS',
  ONBOARDING_RETRY_ADDRESS = 'ONBOARDING_RETRY_ADDRESS',
  ONBOARDING_COMPLETE = 'ONBOARDING_COMPLETE',
}
